project_id = "habawndmitwvdgesjbrt"

[functions.track-access]
verify_jwt = false

[functions.check-access]
verify_jwt = false

[functions.get-leaderboard]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
